window.MOCK_USERS = [
  { email: "gustavo.rebollo@mecanicatek.com", nombre: "Gustavo Rebollo Cervantes", rol: "Instructor RegiÃ³n Centro", region: "Centro", status: "Activo" },
  { email: "warren.elizondo@mecanicatek.com", nombre: "Warren Alfonso Elizondo Villarreal", rol: "Consulta", region: "Os", status: "Activo" },
  { email: "juan.camarillo@mecanicatek.com", nombre: "Juan Pedro Camarillo Estrada", rol: "Instructor RegiÃ³n Norte", region: "Norte", status: "Activo" },
  { email: "eduardo.perezzavala@mecanicatek.com", nombre: "Eduardo Perez Zavala", rol: "Admin", region: "Os", status: "Activo" },
  { email: "fernando.monreal@mecanicatek.com", nombre: "Fernando Monreal Morales", rol: "Admin", region: "Os", status: "Activo" }
];

window.MOCK_RECORDS = [
  { "hora de inicio": "2026-04-10 08:00", "hora de finalizacion": "2026-04-10 10:00", "total de puntos": 15, "N. de pers.": "10458", "Nombre empl": "Marco Ruiz", "TXT breve": "Seguridad elÃ©ctrica", "Puesto": "TÃ©cnico", "Region": "Norte", "Text DivP": "Servicio", "Instructor": "Juan Pedro Camarillo Estrada", "tipo de examen": "PrÃ¡ctico", "horas": 2, "status": "Completado" },
  { "hora de inicio": "2026-04-10 11:00", "hora de finalizacion": "2026-04-10 12:30", "total de puntos": 12, "N. de pers.": "10459", "Nombre empl": "Luis Tamez", "TXT breve": "Motores diesel", "Puesto": "Supervisor", "Region": "Norte", "Text DivP": "Operaciones", "Instructor": "Juan Pedro Camarillo Estrada", "tipo de examen": "TeÃ³rico", "horas": 1.5, "status": "Completado" },
  { "hora de inicio": "2026-04-11 09:00", "hora de finalizacion": "2026-04-11 12:00", "total de puntos": 20, "N. de pers.": "20412", "Nombre empl": "Karla Leal", "TXT breve": "DiagnÃ³stico avanzado", "Puesto": "TÃ©cnico", "Region": "Centro", "Text DivP": "Postventa", "Instructor": "Gustavo Rebollo Cervantes", "tipo de examen": "PrÃ¡ctico", "horas": 3, "status": "Completado" },
  { "hora de inicio": "2026-04-11 13:00", "hora de finalizacion": "2026-04-11 14:30", "total de puntos": 8, "N. de pers.": "20413", "Nombre empl": "Paola GarcÃ­a", "TXT breve": "Motores gasolina", "Puesto": "Asesor", "Region": "Centro", "Text DivP": "Ventas", "Instructor": "Gustavo Rebollo Cervantes", "tipo de examen": "TeÃ³rico", "horas": 1.5, "status": "Pendiente" },
  { "hora de inicio": "2026-04-12 08:30", "hora de finalizacion": "2026-04-12 10:30", "total de puntos": 17, "N. de pers.": "30511", "Nombre empl": "Emilio ChÃ¡vez", "TXT breve": "Sistema hidrÃ¡ulico", "Puesto": "TÃ©cnico", "Region": "BajÃ­o", "Text DivP": "Servicio", "Instructor": "Fernando Monreal Morales", "tipo de examen": "PrÃ¡ctico", "horas": 2, "status": "Completado" },
  { "hora de inicio": "2026-04-12 11:00", "hora de finalizacion": "2026-04-12 13:00", "total de puntos": 10, "N. de pers.": "30512", "Nombre empl": "Diego Rojas", "TXT breve": "Normas de seguridad", "Puesto": "TÃ©cnico", "Region": "BajÃ­o", "Text DivP": "Seguridad", "Instructor": "Fernando Monreal Morales", "tipo de examen": "TeÃ³rico", "horas": 2, "status": "Completado" },
  { "hora de inicio": "2026-04-13 09:00", "hora de finalizacion": "2026-04-13 11:30", "total de puntos": 16, "N. de pers.": "40105", "Nombre empl": "Daniela LeÃ³n", "TXT breve": "InspecciÃ³n preoperativa", "Puesto": "Supervisor", "Region": "Sureste", "Text DivP": "Operaciones", "Instructor": "Warren Alfonso Elizondo Villarreal", "tipo de examen": "TeÃ³rico", "horas": 2.5, "status": "Completado" },
  { "hora de inicio": "2026-04-13 12:00", "hora de finalizacion": "2026-04-13 15:00", "total de puntos": 24, "N. de pers.": "40106", "Nombre empl": "Rosa Pacheco", "TXT breve": "Mantenimiento preventivo", "Puesto": "TÃ©cnico", "Region": "Sureste", "Text DivP": "Taller", "Instructor": "Warren Alfonso Elizondo Villarreal", "tipo de examen": "PrÃ¡ctico", "horas": 3, "status": "Completado" },
  { "hora de inicio": "2026-04-14 10:00", "hora de finalizacion": "2026-04-14 11:30", "total de puntos": 11, "N. de pers.": "50931", "Nombre empl": "Ricardo Mena", "TXT breve": "Lectura de cÃ³digos", "Puesto": "TÃ©cnico", "Region": "Golfo", "Text DivP": "DiagnÃ³stico", "Instructor": "Eduardo Perez Zavala", "tipo de examen": "TeÃ³rico", "horas": 1.5, "status": "Pendiente" },
  { "hora de inicio": "2026-04-14 12:00", "hora de finalizacion": "2026-04-14 14:30", "total de puntos": 18, "N. de pers.": "50932", "Nombre empl": "Ana SolÃ­s", "TXT breve": "Tren motriz", "Puesto": "TÃ©cnico", "Region": "Golfo", "Text DivP": "Servicio", "Instructor": "Eduardo Perez Zavala", "tipo de examen": "PrÃ¡ctico", "horas": 2.5, "status": "Completado" },
  { "hora de inicio": "2026-04-15 09:00", "hora de finalizacion": "2026-04-15 10:00", "total de puntos": 6, "N. de pers.": "61241", "Nombre empl": "Laura Nieto", "TXT breve": "InducciÃ³n tÃ©cnica", "Puesto": "TÃ©cnico", "Region": "Centro", "Text DivP": "Capital humano", "Instructor": "Gustavo Rebollo Cervantes", "tipo de examen": "DiagnÃ³stico", "horas": 1, "status": "Completado" },
  { "hora de inicio": "2026-04-15 11:00", "hora de finalizacion": "2026-04-15 12:00", "total de puntos": 7, "N. de pers.": "71220", "Nombre empl": "Julio Castro", "TXT breve": "TelemÃ¡tica", "Puesto": "TÃ©cnico", "Region": "Norte", "Text DivP": "IngenierÃ­a", "Instructor": "Juan Pedro Camarillo Estrada", "tipo de examen": "DiagnÃ³stico", "horas": 1, "status": "Pendiente" }
];
